baseURL = 'https://laduecs.github.io/'
languageCode = 'en-us'
title = 'Ladue CS Club'
theme = 'terminal'
[params]
  # set theme to full screen width
  # fullWidthTheme = true
  # center theme with default width
  centerTheme = true
