baseURL = 'https://laduecs.github.io/'
languageCode = 'en-us'
title = 'Ladue CS Club'
theme = 'terminal'
[params]
  # set theme to full screen width
  # fullWidthTheme = true
  # center theme with default width
  centerTheme = true
  themeColor = 'blue'

[languages]
  [languages.en]
    title = "LadueCS"
    subtitle = "The Ladue Computer Science Club"

    [languages.en.params.logo]
      logoText = "LadueCS"
